server:
  port: 8080
  redirect_uri: "https://swan-cool-tiger.ngrok.io/oauth/callback"

strava:
  url: "https://www.strava.com"

athlete:
  run:
    threshold_hr: 171
  swim:
    threshold_hr: 144
  bike:
    threshold_hr: 164