strava:
  client_id: "124662"
  client_secret: "84a23700e1619da486a0c9ee75c6e321a347213b"
openai:
  api_key: "sk-svcacct-SY28j3zmYSlFqhhresN2g_tUeCiRHnIJZ7_0KXbResZ5T3BlbkFJir7QyJvgYCIhWgnYjbzD30TYBE_UaQtwoSqgXaBs9aQA"
